[package]
name = "nomos-platform-std"
version = "0.1.0"
description = "The std implementation of the platform port."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nomos-platform = { workspace = true }

[lints]
workspace = true
