// How a projection narrows what it selects, and what it renders it as.
mod filter;
mod format;

pub use filter::Filter;
pub use format::Format;

// What a projection is made of: what goes in, the items it selects, the content it
// carries, and what comes out.
mod content;
mod input;
mod item;
mod output;

pub use content::Content;
pub use input::Input;
pub use item::{Item, Name, Value};
pub use output::Output;

use crate::Section;
use serde::Serialize;

pub const GENERATED_FILE_NOTICE: &str =
    "Generated by nomos spec project. Edits here are discarded on the next build; \
     change the store and rebuild.";

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Projection
{
    pub profile: String,
    pub title: String,
    pub format: Format,
    pub output: String,
    pub sections: Vec<Section>,
    pub inputs: Vec<Input>,
}

impl Projection
{
    #[must_use]
    pub fn Items(&self) -> usize
    {
        return self.sections.iter().map(|section| return section.items.len()).sum();
    }

    #[must_use]
    pub fn Inputs_Digest(&self) -> String
    {
        use nomos_spec_model::ContentHash;

        let mut material = String::new();
        for input in &self.inputs
        {
            material.push_str(input.content.Label());
            material.push('\u{1f}');
            material.push_str(&input.identity);
            material.push('\u{1f}');
            material.push_str(&input.hash);
            material.push('\n');
        }

        return ContentHash::Of(&material).As_String_Slice().to_owned();
    }
}

#[cfg(test)]
mod tests
{
    use super::*;

    /// The two items in the first section of [`Two_Section_Projection`] plus the one in the
    /// second.
    const ITEMS_ACROSS_TWO_SECTIONS: usize = 3;

    #[test]
    fn Test_Items_Should_Sum_Every_Sections_Length()
    {
        let projection = Two_Section_Projection();

        assert_eq!(projection.Items(), ITEMS_ACROSS_TWO_SECTIONS);
    }

    #[test]
    fn Test_Inputs_Digest_Should_Change_When_An_Input_Hash_Changes()
    {
        let mut projection = Two_Section_Projection();
        let original = projection.Inputs_Digest();

        projection
            .inputs
            .get_mut(0)
            .expect("Two_Section_Projection builds at least one input")
            .hash = "sha256:cc".to_owned();

        assert_ne!(projection.Inputs_Digest(), original);
    }

    fn Two_Section_Projection() -> Projection
    {
        return Projection {
            profile: "one".to_owned(),
            title: "One".to_owned(),
            format: Format::Markdown,
            output: "one.md".to_owned(),
            sections: vec![
                Section {
                    title: "Nodes".to_owned(),
                    content: Content::Nodes,
                    items: vec![Item::Of("A"), Item::Of("B")],
                },
                Section {
                    title: "Statements".to_owned(),
                    content: Content::Statements,
                    items: vec![Item::Of("C")],
                },
            ],
            inputs: vec![
                Input {
                    content: Content::Nodes,
                    identity: "A".to_owned(),
                    hash: "sha256:aa".to_owned(),
                },
                Input {
                    content: Content::Statements,
                    identity: "C".to_owned(),
                    hash: "sha256:bb".to_owned(),
                },
            ],
        };
    }
}
