use crate::profile::{Content, Format};
use nomos_spec_model::ContentHash;
use serde::{Deserialize, Serialize};

pub const DO_NOT_EDIT: &str =
    "Generated by nomos spec project. Edits here are discarded on the next build; \
     change the store and rebuild.";

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize)]
pub struct Item
{
    pub identity: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub fields: Vec<(String, String)>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
}

impl Item
{
    #[must_use]
    pub fn Of(identity: &str) -> Self
    {
        return Self {
            identity: identity.to_owned(),
            fields: Vec::new(),
            body: None,
        };
    }

    #[must_use]
    pub fn With(mut self, name: &str, value: &str) -> Self
    {
        self.fields.push((name.to_owned(), value.to_owned()));

        return self;
    }

    #[must_use]
    pub fn Carrying(mut self, body: &str) -> Self
    {
        self.body = Some(body.to_owned());

        return self;
    }

    #[must_use]
    pub fn Field(&self, name: &str) -> Option<&str>
    {
        return self
            .fields
            .iter()
            .find(|(field, _)| return field == name)
            .map(|(_, value)| return value.as_str());
    }

    #[must_use]
    pub fn Digest(&self) -> String
    {
        let mut material = self.identity.clone();
        for (name, value) in &self.fields
        {
            material.push('\u{1f}');
            material.push_str(name);
            material.push('\u{1f}');
            material.push_str(value);
        }
        if let Some(body) = &self.body
        {
            material.push('\u{1e}');
            material.push_str(body);
        }

        return ContentHash::Of(&material).As_Str().to_owned();
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Section
{
    pub title: String,
    pub content: Content,
    pub items: Vec<Item>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct Input
{
    pub content: Content,
    pub identity: String,
    pub hash: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Projection
{
    pub profile: String,
    pub title: String,
    pub format: Format,
    pub output: String,
    pub sections: Vec<Section>,
    pub inputs: Vec<Input>,
}

impl Projection
{
    #[must_use]
    pub fn Items(&self) -> usize
    {
        return self.sections.iter().map(|section| return section.items.len()).sum();
    }

    #[must_use]
    pub fn Inputs_Digest(&self) -> String
    {
        let mut material = String::new();
        for input in &self.inputs
        {
            material.push_str(input.content.Label());
            material.push('\u{1f}');
            material.push_str(&input.identity);
            material.push('\u{1f}');
            material.push_str(&input.hash);
            material.push('\n');
        }

        return ContentHash::Of(&material).As_Str().to_owned();
    }
}
