// How a projection narrows what it selects, and what it renders it as.
mod filter;
mod format;

pub use filter::Filter;
pub use format::Format;

// What a projection is made of: what goes in, the items it selects, the content it
// carries, and what comes out.
mod content;
mod input;
mod item;
mod output;

pub use content::Content;
pub use input::Input;
pub use item::{Item, Name, Value};
pub use output::Output;

use crate::Section;
use serde::Serialize;

pub const GENERATED_FILE_NOTICE: &str =
    "Generated by nomos spec project. Edits here are discarded on the next build; \
     change the store and rebuild.";

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Projection
{
    pub profile: String,
    pub title: String,
    pub format: Format,
    pub output: String,
    pub sections: Vec<Section>,
    pub inputs: Vec<Input>,
}

impl Projection
{
    #[must_use]
    pub fn Items(&self) -> usize
    {
        return self.sections.iter().map(|section| return section.items.len()).sum();
    }

    #[must_use]
    pub fn Inputs_Digest(&self) -> String
    {
        use nomos_spec_model::ContentHash;

        let mut material = String::new();
        for input in &self.inputs
        {
            material.push_str(input.content.Label());
            material.push('\u{1f}');
            material.push_str(&input.identity);
            material.push('\u{1f}');
            material.push_str(&input.hash);
            material.push('\n');
        }

        return ContentHash::Of(&material).As_String_Slice().to_owned();
    }
}
