//! P3: the same store renders the same bytes, whoever built it and wherever they built it.
//!
//! Four things could reach the output and must not — a second build, a bundle round trip,
//! the order the store was written in, and the machine holding it. Each is asserted over the
//! whole catalogue rather than over one profile, because a renderer that leaks one of them
//! leaks it in exactly one format.

use crate::store::{For_Building, Order, Populated, Populated_In_Order, Shipped};
use nomos_spec_bundle::{Bundle, Export, Import_Bundle};
use nomos_spec_project::{Build, GENERATED_FILE_NOTICE};

/// P3, first half.
#[test]
fn Test_A_Rebuild_Should_Be_Byte_Identical()
{
    let store = Populated();

    for profile in Shipped().Profiles()
    {
        let buildable = For_Building(profile);
        let first = Build(&store, &buildable).expect("builds");
        let second = Build(&store, &buildable).expect("rebuilds");

        assert_eq!(first.body, second.body, "{} does not rebuild to itself", profile.id);
        assert_eq!(first.Sidecar().expect("stamps"), second.Sidecar().expect("stamps"));
    }
}

/// P3, second half.
#[test]
fn Test_Building_From_A_Fresh_Import_Should_Equal_Building_From_The_Original()
{
    use nomos_spec_store::SpecificationStore;

    let source = Populated();
    let bundle = Export(&source).expect("exports").Write().expect("writes");
    let mut rebuilt = SpecificationStore::In_Memory().expect("opens");
    Import_Bundle(&mut rebuilt, &Bundle::Parse(&bundle).expect("parses")).expect("imports");

    for profile in Shipped().Profiles()
    {
        let buildable = For_Building(profile);
        let original = Build(&source, &buildable).expect("builds from the original");
        let imported = Build(&rebuilt, &buildable).expect("builds from the import");

        assert_eq!(
            original.body, imported.body,
            "{} renders differently after a bundle round trip",
            profile.id
        );
        assert_eq!(original.stamp, imported.stamp, "{}", profile.id);
    }
}

/// Insertion order decides `uid`, and nothing in a projection may be ordered by one.
#[test]
fn Test_Insertion_Order_Should_Not_Reach_The_Output()
{
    let forwards = Populated_In_Order(Order::Forwards);
    let backwards = Populated_In_Order(Order::Backwards);

    for profile in Shipped().Profiles()
    {
        let buildable = For_Building(profile);
        let first = Build(&forwards, &buildable).expect("builds");
        let second = Build(&backwards, &buildable).expect("builds");

        assert_eq!(
            first.body, second.body,
            "{} orders its output by the order the store was written in",
            profile.id
        );
    }
}

#[test]
fn Test_Every_Body_Should_Be_Lf_Utf8_Without_A_Bom()
{
    let store = Populated();

    for profile in Shipped().Profiles()
    {
        let output = Build(&store, &For_Building(profile)).expect("builds");

        assert!(!output.body.contains('\r'), "{} carries a carriage return", profile.id);
        assert!(
            !output.body.starts_with('\u{feff}'),
            "{} starts with a byte order mark",
            profile.id
        );
        assert!(
            !output.Sidecar().expect("stamps").contains('\r'),
            "{}: the sidecar carries a carriage return",
            profile.id
        );
    }
}

#[test]
fn Test_Every_Body_Should_Declare_Itself_Generated()
{
    let store = Populated();

    for profile in Shipped().Profiles()
    {
        let output = Build(&store, &For_Building(profile)).expect("builds");

        Assert_Declares_Itself_Generated(&output.body, &profile.id);
    }
}

/// A body has to say it is generated, say it must not be edited, and carry the sentence that
/// explains the marker rather than the marker on its own.
fn Assert_Declares_Itself_Generated(body: &str, id: &str)
{
    assert!(
        body.contains("nomos_generated") || body.contains("nomos-generated"),
        "{id} does not say it is generated"
    );
    assert!(
        body.contains("do_not_edit") || body.contains("do-not-edit"),
        "{id} does not say it must not be edited"
    );
    assert!(
        body.contains(GENERATED_FILE_NOTICE.get(..40).unwrap_or(GENERATED_FILE_NOTICE))
            || body.contains("Generated by nomos"),
        "{id} carries the marker without the sentence that explains it"
    );
}

/// The done-when, checked against the environment this build actually runs in rather than
/// against a pattern that guesses what one looks like.
#[test]
fn Test_No_Body_Should_Carry_This_Machine()
{
    let store = Populated();
    let directory = std::env::current_dir().expect("has a working directory");
    let temporary = std::env::temp_dir();
    let host = std::env::var("COMPUTERNAME")
        .or_else(|_| return std::env::var("HOSTNAME"))
        .unwrap_or_default();

    for profile in Shipped().Profiles()
    {
        let output = Build(&store, &For_Building(profile)).expect("builds");

        for environmental in [
            directory.display().to_string(),
            temporary.display().to_string(),
            host.clone(),
        ]
        {
            if environmental.trim().is_empty()
            {
                continue;
            }
            assert!(
                !output.body.contains(&environmental),
                "{} carries {environmental}, so the output depends on the machine that built it",
                profile.id
            );
        }

        assert!(
            !output.body.contains("://") && !output.body.contains(":\\"),
            "{} carries an absolute location",
            profile.id
        );
    }
}
